### ISSUE TITLE
Binder shows examples inside docker when a Dockerfile is used

### ISSUE THREAD

**Issue by BoPeng** [binder-examples/jupyter-sos#3]
In the [master branch of jupyter-sos](https://github.com/binder-examples/jupyter-sos/blob/master/README.md), I have used a [Docker file](https://github.com/binder-examples/jupyter-sos/blob/master/Dockerfile) that is derived from [the sos-notebook dockerfile](https://github.com/vatlab/SoS/blob/master/development/docker-notebook/Dockerfile), which has been used by our live tmpnb server. It seems to be working all right but binder shows the examples inside the docker image, not the ones on  [jupyter-sos](https://github.com/binder-examples/jupyter-sos/blob/master/README.md). Is there anyway for me to change this behavior?

@choldgraf

**Comment by choldgraf** [comment]
hey - check out the last section here:

https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html#preparing-your-dockerfile

specifically the part about "copy the files into the home directory"

**Comment by BoPeng** [comment]
It works! Now the master branch also works and we have three working configurations. I will stop now and add more interesting examples and/or configurations later on.

**Comment by choldgraf** [comment]
woot - really nice @BoPeng , thanks! We should update this repo to use config files once we hash out the composability a bit more!

**Comment by BoPeng** [comment]
Yes, that is the way to go. I have been talking to the [codeocean](https://codeocean.com/) guys. They currently use a GUI with similar functionalities to repo2docker and are facing the same compatibility issues when trying to combine multiple jupyter kernels for SoS. A single "SoS" image is possible but it would be a lot of work to upgrade or tweak individual kernels included in the image.

BTW, I have just added the binder icon to sos homepage and pointed it to this repo.

[![image](https://user-images.githubusercontent.com/9889312/46890901-d65bf100-ce2d-11e8-8750-4f68e83e8983.png)](https://vatlab.github.io/sos-docs/)

**Comment by BoPeng** [comment]
Just submitted a ticket for the compatibility issue (https://github.com/jupyter/repo2docker/issues/437).

**Comment by choldgraf** [comment]
hooray! sounds great
